---
- name: Create .rsdns directory
  file: path=/root/.rsdns state=directory

- name: place rs_dns tar
  unarchive: src=rs_dns.tar dest=/root/.rsdns

- name: create rs_dns.sh
  template: src=rs_dns.sh.j2 dest=/root/.rsdns/rs_dns.sh mode=0700

- name: install reqs debian
  include: install_jq_debian.yml
  when: ansible_distribution == "Ubuntu" and "rpi" not in ansible_hostname

- name: install jq rhel
  include: install_jq_rhel.yml
  when: ansible_distribution == "Fedora" and "rpi" not in ansible_hostname

  # TODO (evanscottgray) write task to install jq on RPI
  
- name: insert rs_dns cron job.
  cron: name="Update DNS" minute="*/5" job="/root/.rsdns/rs_dns.sh >>/var/log/cronrun 2>&1"

- name: run rs_dns manually
  shell: /root/.rsdns/rs_dns.sh executable=/bin/bash
