---
- name: restart fail2ban
  service: name=fail2ban state=restarted

- name: restart firewalld 
  service: name=firewalld state=restarted

- name: restart ssh
  service: name={{ ssh_service_name }} state=restarted
  when: ssh_config|changed
