---
- name: Install Vim
  apt: pkg=vim state=latest

- name: Add .vimrc
  copy: src=vimrc dest=/root/.vimrc

- name: Add public keys.
  authorized_key: user=root
                  key="{{ item }}"
  with_file:
    - "public_keys/evan_rax_mac.pub"
    - "public_keys/travis_personal_mbp.pub"

- name: Install fail2ban
  apt: pkg=fail2ban state=latest

- name: Write fail2ban config file.
  template: src="fail2ban/jail.conf.j2" dest=/etc/fail2ban/jail.conf
  notify:
    - restart fail2ban

- name: Ensure fail2ban is running
  service: name=fail2ban state=started

- name: Write openssh config file. Yay key based auth..
  template: src="openssh/sshd_config.j2" dest=/etc/ssh/sshd_config
  register: ssh_config
  

- name: restart sshd
  command: service ssh restart
  when: ssh_config|changed

- name: Create New Metadata Fact
  set_fact:
    additional_metadata:
      ansible_ssh_port: "{{ ssh_port }}"
